In [1]:
print("hello")

hello


In [6]:
import numpy as np
print(np.__version__)
import pandas as pd
print(pd.__version__)

2.1.0
2.2.2


In [11]:
n = np.zeros((2,3),dtype = int)
n

array([[0, 0, 0],
       [0, 0, 0]])

In [9]:
n.dtype

dtype('int64')

In [18]:
arr = np.array([1,2,3,4],ndmin=2)
print(arr)

[[1 2 3 4]]


In [22]:
arr = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])

print(arr[1, 1, 2])

12


In [25]:
arr = np.array([[1,2,3,4,5], [6,7,8,9,10]])

print('Last element from 2nd dim: ', arr[0, -2])

Last element from 2nd dim:  4


In [1]:
arr = np.array([1, 2, 3, 4, 5, 6, 7])
print(arr[1:7:2])

NameError: name 'np' is not defined

In [28]:
arr = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]])

print(arr[1, 1:4])

[7 8 9]


In [34]:
arr = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]])

print(arr[1:3, 3])

[9]


In [37]:
arr = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]])

print(arr[0:3, 1:4])

[[2 3 4]
 [7 8 9]]


In [38]:
arr = np.array([1.1, 2.1, 3.1])

newarr = arr.astype('i')

print(newarr)
print(newarr.dtype)

[1 2 3]
int32


In [4]:


arr = np.array([1, 2, 3, 4], dtype='S')

print(arr)
print(arr.dtype)

[b'1' b'2' b'3' b'4']
|S1


In [7]:


arr = np.array([1, 2, 3, 4], dtype='i8')

print(arr)
print(arr.dtype)

[1 2 3 4]
int64


In [9]:


arr = np.array([4.1, 2.1, 3.1])

newarr = arr.astype('i')

print(newarr)
print(newarr.dtype)

[4 2 3]
int32


In [10]:


arr = np.array([1.1, 2.1, 3.1])

newarr = arr.astype(int)

print(newarr)
print(newarr.dtype)

[1 2 3]
int64


In [11]:


arr = np.array([1, 2, 3, 4, 5])
x = arr.copy()
arr[0] = 42

print(arr)
print(x)

[42  2  3  4  5]
[1 2 3 4 5]


In [12]:


arr = np.array([1, 2, 3, 4], ndmin=5)

print(arr)
print('shape of array :', arr.shape)

[[[[[1 2 3 4]]]]]
shape of array : (1, 1, 1, 1, 4)


In [21]:


arr = np.array([1, 2, 3, 4, 5, 6, 7, 8,9,10,11,12])

newarr = arr.reshape(2, 2,-1)

print(newarr)

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]


In [22]:


arr = np.array([[1, 2, 3], [4, 5, 6]])

newarr = arr.reshape(-1)

print(newarr)

[1 2 3 4 5 6]


In [30]:

arr = np.array([[1, 2, 3,4], [4, 5, 6,7]])
newarr = arr.reshape(2,4)
print(newarr)

[[1 2 3 4]
 [4 5 6 7]]


In [32]:

arr = np.array([[1, 2, 3,4], [4, 5, 6,7]])
for i in np.nditer(arr):
    print(i)

1
2
3
4
4
5
6
7


In [33]:

arr = np.array([[1, 2, 3,4], [4, 5, 6,7]])
for idx,i in np.ndenumerate(arr):
    print(idx,i)

(0, 0) 1
(0, 1) 2
(0, 2) 3
(0, 3) 4
(1, 0) 4
(1, 1) 5
(1, 2) 6
(1, 3) 7


In [42]:


arr1 = np.array([1, 2, 3, 4])

arr2 = np.array([5, 6, 7, 8])
arr = np.concatenate((arr1,arr2),axis=0)
print(arr)

[1 2 3 4 5 6 7 8]


In [46]:


arr1 = np.array([[1, 2], [3, 4]])
arr2 = np.array([[5, 6], [7, 8]])
arr3 = np.array([[9, 10], [11, 12]])

# Concatenate along axis 0 (rows)
result_axis_0 = np.concatenate((arr1, arr2,arr3), axis=0)

# Concatenate along axis 1 (columns)
result_axis_1 = np.concatenate((arr1, arr2,arr3), axis=1)
print(result_axis_0)
print(result_axis_1)

[[ 1  2]
 [ 3  4]
 [ 5  6]
 [ 7  8]
 [ 9 10]
 [11 12]]
[[ 1  2  5  6  9 10]
 [ 3  4  7  8 11 12]]


In [47]:


# Two 3D arrays
arr1 = np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])
arr2 = np.array([[[9, 10], [11, 12]], [[13, 14], [15, 16]]])

# Concatenate along axis=2 (columns within each slice)
result_axis_2 = np.concatenate((arr1, arr2), axis=2)
print(result_axis_2)


[[[ 1  2  9 10]
  [ 3  4 11 12]]

 [[ 5  6 13 14]
  [ 7  8 15 16]]]


In [6]:

arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9], [10, 11, 12], [13, 14, 15], [16, 17, 18]])

newarr = np.hsplit(arr, 3)

print(newarr)


[array([[ 1],
       [ 4],
       [ 7],
       [10],
       [13],
       [16]]), array([[ 2],
       [ 5],
       [ 8],
       [11],
       [14],
       [17]]), array([[ 3],
       [ 6],
       [ 9],
       [12],
       [15],
       [18]])]
